# Generated by Django 4.0 on 2025-04-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=255)),
                ('hero', models.CharField(max_length=255)),
                ('heroine', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('releaseyear', models.IntegerField()),
            ],
        ),
    ]
